language: node_js
node_js:
- node
git:
  depth: false
script:
- npm run test
- npm run build
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAIXAPOLMFA5OFOBDA
  secret_access_key:
    secure: obEmjCghSg4sWFaFQ1P9sTfMPXCPTarJSXEtxovaDGTccpebNXv9PSWVKYfiJm8kNmwa8oyd08Z+bsFTOEqZbXgDzT2AoF9c6Z6xopXX7xaoXipR768MUPhqi8U6ZQPpCj2xm6TUryx4FCGdQXA4/OKt40agGC5d/fsXKCVMoUShdXF2c5W0w19nHr1KVmNy4XQTmsnMO8766RE+FMwLWYf2SgW9EXx9zp3wfuw8Sg8XcoMtfOwqnXmVKB83jcIUqujmTArHndsVtYdchWrK1K+HbN8Mb5/pCEzUwDNoWl/xl1nhNTEWpWXiZYm/jG9QZdmx5nNAaqKhxG6CMqrvD+QbgxIs5vaYW8VzJt7jwN3DaOTetoUanl4bxiTQ+sVF7NaElWAh+vsqAXZWTO7mPWa+JlZ8IlQA/kN51hk09eEd4Wdf7t092PIgoy8nzEjtMzXshtQmpmJ6hfNbWrR1tpusuPBKzFF8PxVPrbaPr9OpmtbD5fzu/fvQBkNnswYW9G3i2Ox+kHLHMGap6yu7iswzDsYSNBQwda+atxfy8fcKOlk+EJMqdNQoCoO/YcaWWxBFB1xnu6kfLUi5pYzTf8ZTtylR3LT2qROlrdEv8esO7dF7j6dYlNFvJfItQLXLozlSBZrQFAWvRRQ3MfZPpBmKZt+zmuNXsDMSPh2IYZk=
  bucket: evanlissoos.com
  region: us-east-2
  local-dir: build
  acl: ''
  on:
    repo: Denman35/evan-portfolio-site
